<?php

/**
 * @file
 * Provides newsroom_connector_service functionality.
 */

use Drupal\migrate\Plugin\MigrationInterface;
use Drupal\migrate\Plugin\MigrateSourceInterface;
use Drupal\migrate\Row;

/**
 * Implements hook_migrate_prepare_row().
 */
function newsroom_connector_service_migrate_prepare_row(
  Row $row,
  MigrateSourceInterface $source,
  MigrationInterface $migration
) {

  // Set title as alt text if it is empty.
  if (strpos($migration->id(), 'newsroom_service_logo_media_translations') !== FALSE || $migration->id() == 'newsroom_service_logo_media') {
    $image_alt = $row->getSourceProperty('image_alt');

    if (empty($image_alt)) {
      $title = $row->getSourceProperty('service_name');
      $row->setSourceProperty('image_alt', $title);
    }
  }
}
