<?php

/**
 * @file
 * Provides newsroom_connector_service functionality.
 */

use Drupal\newsroom_connector_service\Plugin\newsroom\NewsroomServiceNewsroomProcessor;

/**
 * Implements hook_entity_delete().
 */
function newsroom_connector_service_taxonomy_term_delete(Drupal\Core\Entity\EntityInterface $entity) {
  if ($entity->bundle() == 'newsroom_service') {
    // Clean up migrations.
    $migration_manager = \Drupal::service('newsroom_connector.migration_manager');
    $migration_manager->cleanUpMigrations(NewsroomServiceNewsroomProcessor::MIGRATION_SERVICE, $entity);

    if ($media = $entity->field_newsroom_service_image->entity) {
      $migration_manager->cleanUpMigrations(NewsroomServiceNewsroomProcessor::MIGRATION_SERVICE_IMAGE_MEDIA, $media);
      if ($file = $media->field_media_image_newsroom->entity) {
        $migration_manager->cleanUpMigrations(NewsroomServiceNewsroomProcessor::MIGRATION_SERVICE_IMAGE, $file);
      }
      $media->delete();
    }
  }
}
