newsroom_connector.settings:
  type: 'config_object'
  label: 'Newsroom connector settings'
  mapping:
    universe_id:
      type: 'string'
      label: 'Universe ID'
    debug:
      type: 'boolean'
      label: 'Debug importers'
    import_disabled:
      type: 'boolean'
      label: 'Disable import'
    base_url:
      type: 'string'
      label: 'Base URL'
    api_key:
      type: 'string'
      label: 'API key'
    subsite:
      type: 'string'
      label: 'Subsite parameter'
