<?php

/**
 * @file
 * Provides nexteuropa_newsroom_item_type functionality.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\StringTranslation\TranslatableMarkup;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_help().
 */
function nexteuropa_newsroom_item_type_help($route_name, RouteMatchInterface $route_match) {
  if ($route_name == 'help.page.token') {
    $output = '<h3>' . t('About') . '</h3>';
    $output .= '<p>' . t('The <a href=":project">Nexteuropa Newsroom Item Type</a> module provides a newsroom item taxonomy vocabulary and importer for it. This module is part of newsroom connector') . '</p>';
    $output .= '<dl>';
    return $output;
  }
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function nexteuropa_newsroom_item_type_form_nexteuropa_newsroom_settings_form_alter(
  &$form,
  FormStateInterface $form_state,
  $form_id
) {

  $config_factory = \Drupal::configFactory();
  $config = $config_factory->get('nexteuropa_newsroom_item_type.settings');

  $form['universe_settings']['type'] = [
    '#type' => 'fieldset',
    '#title' => new TranslatableMarkup('Newsroom item type settings'),
  ];
  $form['universe_settings']['type']['type_import_script'] = [
    '#type' => 'textfield',
    '#title' => _nexteuropa_newsroom_item_type_translate("Import type script name:"),
    '#default_value' => $config->get('type_import_script'),
    '#required' => TRUE,
  ];
  $form['universe_settings']['type']['type_import_segment'] = [
    '#type' => 'textfield',
    '#title' => _nexteuropa_newsroom_item_type_translate("URL chunk for single type import:"),
    '#default_value' => $config->get('type_import_segment'),
    '#required' => TRUE,
  ];

  $form['actions']['submit']['#submit'][] = '_nexteuropa_newsroom_item_type_save_settings';
}

/**
 * Provides translated string.
 *
 * @param string $string
 *   String to be translated.
 * @param array $arguments
 *   Dynamics parts of the string.
 *
 * @return \Drupal\Core\StringTranslation\TranslatableMarkup
 *   Trnslatable object.
 */
function _nexteuropa_newsroom_item_type_translate($string, $arguments = []) {
  return new TranslatableMarkup($string, $arguments);
}

/**
 * Submit handler for newsroom type settings.
 *
 * @param array $form
 *   Form array.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   Form state.
 */
function _nexteuropa_newsroom_item_type_save_settings(array $form, FormStateInterface $form_state) {
  $config_factory = \Drupal::configFactory();

  $config = $config_factory->getEditable('nexteuropa_newsroom_item_type.settings');
  $config->set('type_import_script', $form_state->getValue('type_import_script'));
  $config->set('type_import_segment', $form_state->getValue('type_import_segment'));
  $config->save();
}
