<?php

/**
 * @file
 * Provides newsroom_connector_type functionality.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\StringTranslation\TranslatableMarkup;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_help().
 */
function newsroom_connector_type_help($route_name, RouteMatchInterface $route_match) {
  if ($route_name == 'help.page.token') {
    $output = '<h3>' . t('About') . '</h3>';
    $output .= '<p>' . t('The <a href=":project">Newsroom Connector Type</a> module provides a newsroom item taxonomy vocabulary and importer for it. This module is part of newsroom connector') . '</p>';
    $output .= '<dl>';
    return $output;
  }
}
